[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | upper_first }}
{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
filter_commits = false
tag_pattern = "v[0-9]*"

commit_parsers = [
  { message = "^chore: bump version", skip = true },
  { message = "^feat", group = "✨ Features" },
  { message = "^fix", group = "🐛 Fixes" },
  { message = "^refactor", group = "♻️ Refactoring" },
  { message = "^perf", group = "⚡ Performance" },
  { message = "^docs", group = "📝 Docs" },
  { message = "^style", group = "🎨 Style" },
  { message = "^test", group = "✅ Tests" },
  { message = "^build", group = "📦 Build" },
  { message = "^ci", group = "👷 CI" },
  { message = "^chore", group = "🧹 Chores" },
  { message = "^revert", group = "⏪ Reverts" },
  { message = ".*", group = "📌 Other" },
]
